### ISSUE TITLE
What do you like doing besides programming?

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/ama#1]

**Comment by SBoudrias** [comment]
Well, I love rock climbing and biking (mostly for leisure and commuting around the city, not really into those 100km ride).

I have [a dog, _César_](https://instagram.com/p/oaG7f6JWuJ/?taken-by=sboudrias), so there's a lot of hanging out in parks and picking up poop.

Otherwise, I like going out eating (using Yelp) and hanging out in bars with friends.

**Comment by sindresorhus** [comment]
> I have a dog, César, so there's a lot of hanging out in parks and picking up poop.

Me too! :)

> Otherwise, I like going out eating **(using Yelp)** and hanging out in bars with friends.

Smooth :p
