### ISSUE TITLE
Most productive programming language

### ISSUE THREAD

**Issue by CarlMungazi** [SBoudrias/ama#25]
Which programming language are you most productive in? What is your favourite feature of that language?

**Comment by SBoudrias** [comment]
Hey, thanks for the question.

Most productive in, definitely JavaScript. But that's mainly because I know it well and I've been mainly working on the frontend side for the last year or so. As for a favorite feature, that's a bit more tricky... Maybe simply anonymous function? Handling functions as value is super powerful, so that's good syntactic sugar compared to how you'd implement similar behavior in Python for example.

But favorite feature of all time is probably Python context manager (`with` statement). This feature is awesome and so so so useful. I do wish JS would implement something similar.

**Comment by CarlMungazi** [comment]
Thank you for your response @SBoudrias. As a follow up question, if you don't mind me asking, how has your use of JS influenced the way you think about Python, and vice versa? I guess, for starters, your knowledge of Python has you wishing JS would implement a similar `with` feature!

**Comment by SBoudrias** [comment]
Python immutable data structures like `namedtuples` probably influence a lot of my take on JS dynamic typing. Immutable data and enforced data structure goes a long way with dynamic typing shortcoming. I think we'll see a lot of strict typing in the near future leveraging ES6 proxies.

But overall, I think python and JS are extremely similar languages with a lot of influence on each other. (es7 decorators, es6 array deconstructions - and on the other way, python future objects and callbacks)
