### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/ama#4]
Screenshot please. I ask everyone this. It tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by SBoudrias** [comment]
Oh wow, I had a great time looking at everyone's!

![homescreen](https://cloud.githubusercontent.com/assets/923865/8563920/fce3101e-24f9-11e5-8d9d-bc063cd39d40.PNG)

I just got an iPhone a couple weeks ago (it was a mistake, I miss my android :()

My current goals in life:
1. Inbox 0 forever
2. Learning a bit of chinese (but I'm not super organized, so that goal might fall apart in a month)

**Comment by SBoudrias** [comment]
Also, why am I still having the phone icon in the dock? That's a real mystery...
