### ISSUE TITLE
What do you do at Yelp?

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/ama#5]

**Comment by SBoudrias** [comment]
When I started I worked on the mobile website. I worked on adding the table reservations feature, and a lot of other stuff.

Right now I mostly work in Python on the backend. My main involvement is around untangling and splitting our huge code base into manageable modules and services. - Well, we've had backend services for a long time, but we're just starting to create Frontend services who're serving complete pages with CSS and scripts. So there's a lot of refactoring/design work involved.

It's also pretty interesting to see how we can scale a huge project for developer happiness. Unit tests for our monolithic code base takes more than an hour to run. This can actually only be achieved because we use a distributed testing system that's splitting tests into bundle and running them separately on a clusters of machines. Each time we extract a new page to service, the tests time only take a couple seconds, and the deploy is almost instantaneous.
