### ISSUE TITLE
Describe your dev environment

### ISSUE THREAD

**Issue by clekkas** [SBoudrias/ama#8]
If I were to take a peek at your laptop, what application/tools will I most likely see?

**Comment by SBoudrias** [comment]
Hey, as editor, I'm using Sublime text. I badly want to switch to Atom, but I found it still too slow for bigger projects (even 1.0).

Otherwise, my usual companion tool is iterm2. I use homebrew extensively to install programs. My usual setup for both Linux and Mac is actually open sourced at SBoudrias/dotfiles

These are pretty much my two main tools.

If you're wondering about programming env itself, I mostly work on Python at work and our dev machines are on a clusters that we ssh into. So I basically use `sshfs` to work on my remote disk with sublime. Then I use `ipdb` extensively for debugging. We use Docker a lot to run decouple systems/tools/test suites.

On the side of logs and analysis, we store our log in an ElasticSearch clusters, and we usually make them searchable through Kibana.

Let me know if you'd like details on a tool in particular.
