### ISSUE TITLE
what programming language would you suggest?

### ISSUE THREAD

**Issue by robbbz** [SBoudrias/ama#9]
I am a javascript developer programming node and browser-side.  Except PHP I don't know any other back-end languages. I want to learn something that I can use for web applications, but also just for other kind of programming. What language would you suggest me to use?

**Comment by SBoudrias** [comment]
Well, every language have good and bad parts. And they all have usage.

I think if you wish to learn a new language, you should try to learn a language that is not related to web development. The thing is all dynamic language kind of look alike. JavaScript is very similar to Python, PHP and Ruby. They have the same programming concepts - even though there's patterns, syntax and ecosystem who're different. In term of code it's very similar, you could learn any of these quickly and be proficient in them (although understanding the ecosystem requires a lot of involvement).

So maybe you should think about learning a core programming language? Like Rust or C, C++. Or an app language likes Objective C, Swift or Java.

If you really want to stick with web dev, I'd say Python. Why? Well PHP is just horrible, and Ruby is kind of dead since the ride of Node.js. Python is still widely use for data science and it have support for asynchronous pattern through tools like twisted which makes it competitive in term of performance.
